export { default as NavBar } from './components/navBar/NavBar'
export { default as MainContent } from './components/contents/MainContent'
export { default as Footer } from './components/footer/Footer'
export { default as Home } from './components/pages/home/Home'
export { default as About } from './components/pages/about/About'
export { default as Contact } from './components/pages/contact/Contact'
export { default as Testimonial } from './components/pages/testimonial/Testimonial'
export { default as Services } from './components/pages/services/Services'
